# 1. workflow name
name: CI

# 2. workflow start
on:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest # 3. configuration

    # 4. step
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build