name: CI
on:
  push:
    branches: [ main, test ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Java 설정
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      # 백엔드 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x be-pettact/api/gradlew
      
      - name: Build with Gradle
        run: |
          cd be-pettact/api
          ./gradlew clean build -x test
      
      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # BE image
      - name: Build and Push Backend Image
        run: |
          cd be-pettact/api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pettact-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pettact-backend:latest
      
      # FE image
      - name: Build and Push Frontend Image
        run: |
          cd fe-pettact
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pettact-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pettact-frontend:latest
